[package]
name = "parkerrust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array-init = "2"
crossbeam = "0.8"
fnv = "1.0.7"
memmap = "0.7"
nohash-hasher = "0.2.0"
rayon = "1.5"
